// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZVqXU1l3dI5yCyyPBB2o8cazo-wVvwcw',
    appId: '1:1062739593139:web:dd2168868280ccec91adc6',
    messagingSenderId: '1062739593139',
    projectId: 'dam-u3-practica2-riders',
    authDomain: 'dam-u3-practica2-riders.firebaseapp.com',
    storageBucket: 'dam-u3-practica2-riders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXw15e3IfTpTs8hH3hDclmTSJkgj0aJU',
    appId: '1:1062739593139:android:c5f70ca8fb9ce3ee91adc6',
    messagingSenderId: '1062739593139',
    projectId: 'dam-u3-practica2-riders',
    storageBucket: 'dam-u3-practica2-riders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vhQFjIzRL9-kkO_eYczaenoGKkqryUc',
    appId: '1:1062739593139:ios:07327d3a9391f53a91adc6',
    messagingSenderId: '1062739593139',
    projectId: 'dam-u3-practica2-riders',
    storageBucket: 'dam-u3-practica2-riders.appspot.com',
    iosBundleId: 'com.example.damU3Practica2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7vhQFjIzRL9-kkO_eYczaenoGKkqryUc',
    appId: '1:1062739593139:ios:724ded51502ef26491adc6',
    messagingSenderId: '1062739593139',
    projectId: 'dam-u3-practica2-riders',
    storageBucket: 'dam-u3-practica2-riders.appspot.com',
    iosBundleId: 'com.example.damU3Practica2.RunnerTests',
  );
}
